version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network

  jupyterlab:
    image: jupyter/datascience-notebook
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
    networks:
      - mongodb_network

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /c/Users/XXXXXXXXXXXX/BIGDATA/data/db   # ruta local donde se guardará la base de datos

networks:
  mongodb_network:
    driver: bridge